### ISSUE TITLE
Logging info to stdout and error to stderr?

### ISSUE THREAD

**Issue by fuine6** [OpenSIPS/docker-opensips#14]
I use the [gelf](https://docs.docker.com/config/containers/logging/gelf/) driver as the logging driver.

Currently opensips write log to stderr (log_stderror=yes).

In my log system, this will be logged as an error (including info and debug).

Is there a solution like this '[-log_debug_stdout=true](https://github.com/GoogleCloudPlatform/cloudsql-proxy#-log_debug_stdouttrue)' ?

[This is a similar problem and their solution.](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/106)

**Comment by razvancrainea** [comment]
Unfortunately no, opensips does not provide this option at all - everything is written to stderr. You should open a feature request for opensips to support this (I find it useful as well :)).
