### ISSUE TITLE
APT Key is not avaliable

### ISSUE THREAD

**Issue by Josh-vxt** [OpenSIPS/docker-opensips#16]
The apt-key command fails.

`apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 049AD65B`

![Screenshot from 2022-01-28 16-22-30](https://user-images.githubusercontent.com/81496353/151481974-ead68623-8cec-4afb-83fb-fca43234f7be.png)

**Comment by Josh-vxt** [comment]
Suggest replacing the command with  
`curl -q https://apt.opensips.org/pubkey.gpg | apt-key add -`

**Comment by razvancrainea** [comment]
Not sure about your issue, but I am confident adding an extra tool (such as `curl`) is not the right solution here. Can you please elaborate your experience, and why you suggest using curl might solve your problem?

**Comment by Josh-vxt** [comment]
For some reason the ubuntu key server no longer has the opensips key.
I suggest using curl as then you can download the key manually without the need for a keyserver.

Here is the output from a `make build` which might shed some light
![Screenshot from 2022-02-03 07-51-59](https://user-images.githubusercontent.com/81496353/152220363-4dc23b48-cd18-4251-9eed-2d49ef0e61ed.png)

After some more investigation it turns out you don't need to install `curl` as `apt-key` supports downloading a key from a url natively. The following command can be used  
`RUN apt-key adv --fetch-keys https://apt.opensips.org/pubkey.gpg`

See this pull request for the solution that will build successfully https://github.com/OpenSIPS/docker-opensips/pull/17

**Comment by razvancrainea** [comment]
Makes sense now, thanks for the detailed explanation!

**Comment by jwarnier** [comment]
FYI, https://github.com/OpenSIPS/docker-opensips/pull/26 is getting rid of apt-key (since it is deprecated).
