### ISSUE TITLE
Makefile not updated

### ISSUE THREAD

**Issue by mehulved** [OpenSIPS/docker-opensips#8]
Makefile hasn't been updated to match the changes committed to Dockerfile in commit d5592ea212275f68a29197afa8e1c3fc45a957c3.
The change https://github.com/OpenSIPS/docker-opensips/commit/d5592ea212275f68a29197afa8e1c3fc45a957c3#diff-3254677a7917c6c01f55212f86c57fbfR9 introduces OPENSIPS_VERSION and OPENSIPS_BUILD instead of VERSION and BUILD. This leads to the Dockerfile only picking the default version and build.
This can be fixed by applying the following patch to Makefile
diff --git a/Makefile b/Makefile
index b31a248..2b28259 100644
--- a/Makefile
+++ b/Makefile
@@ -8,8 +8,8 @@ all: build start
 .PHONY: build start
 build:
        docker build \
-               --build-arg=BUILD=$(OPENSIPS_BUILD) \
-               --build-arg=VERSION=$(OPENSIPS_VERSION) \
+               --build-arg=OPENSIPS_BUILD=$(OPENSIPS_BUILD) \
+               --build-arg=OPENSIPS_VERSION=$(OPENSIPS_VERSION) \
                --tag="opensips/opensips:$(OPENSIPS_DOCKER_TAG)" \

**Comment by razvancrainea** [comment]
Closed via #9 , thanks for the PR.
